# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d6ba207f956949e55e8009bc5ea6be250e60c53b0de2f1f2cfed35c1181123d464f8fd36f7fd2ccebbd4311a94bfc111d916bdd0ea26e83ab2e219abcdc1045

test:
  secret_key_base: acae987691d943b6396f696e1e5355761290a4fe1705e655bb42a06a73ee1cf6fb38e1c0dff52d0e13c85343260313849aeda1c6a4355a6163c3e2b4d8fdc19d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
